### ISSUE TITLE
Can't Connect to Bridge

### ISSUE THREAD

**Issue by austin3410** [studioimaginaire/phue#121]
Whenever I use the first 2 commands I get an error. I'm extremely new to this so I apologize for my ignorance.
`
>>>from phue import Bridge
>>> b = Bridge("10.10.10.11")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "phue.py", line 629, in __init__
    self.connect()
  File "phue.py", line 752, in connect
    self.register_app()
  File "phue.py", line 720, in register_app
    'The link button has not been pressed in the last 30 seconds.')
phue.PhueRegistrationException
`

Am I just being stupid and missing something? I cloned the repo to a folder, ran the setup with python and then started the python interpreter in the same directory.

Any advice would be appreciated :)

**Comment by demosdemon** [comment]
The very first time you interact with the hub, you need to press the button within thirty seconds before calling that code to authenticate. After that, the `Bridge` object saves its unique username so that it may make future calls without needing to press the button.

**Comment by tremby** [comment]
Where does it save to?

**Comment by pacobyte** [comment]
@tremby On Windows, I believe it saves to your `%USERPROFILE%` folder.

**Comment by bmedicke** [comment]
You can check where it gets saved to for your OS here:

https://github.com/studioimaginaire/phue/blob/00c85d8ce9790d7cc794d277af2d153c92c6009c/phue.py#L609-L616

**Comment by tremby** [comment]
That's important to know when getting a new bridge. I suggest putting it somewhere in the readme.

**Comment by Bashkit** [comment]
Just ran into this issue after resetting bridge to factory defaults. Once you reset your bridge you must also delete the python_hue file in your user dir, then use the connect() command again. Push the bridge button and run connect() again.

**Comment by zjgcainiao** [comment]
To connect a bridge, you have to use both the ip_address and the username
one example is `b=Bridge("192.168.0.20","sew45dsre3435esdwe").
To find the username on a hue bridge on a local ethernet, open the `https://discovery.meethue.com/` and write down the id.

**Comment by YYY003** [comment]
> To connect a bridge, you have to use both the ip_address and the username
> one example is `b=Bridge("192.168.0.20","sew45dsre3435esdwe")`
> To find the username on a hue bridge on a local ethernet, open the `https://discovery.meethue.com/` and write down the id.

Despite trying this nothing saves me from this:

ERROR: unauthorized user for light 9

Any idea?

**Comment by YouAreSoBeterBed** [comment]
Hi, I see this is a few years ago and I have the same problem now, I accidentally deleted Phue via my philips hue bridge but can't connect anymore, did you find an answer?

**Comment by natcl** [comment]
Did you press the link button ?

**Comment by mindheist** [comment]
Yeah .. still having the same problem.. but worked after hitting the button on the hue bridge.

**Comment by LaughingMaann** [comment]
i also get the same error. but this only happened after using a different host machine to connect to the same bridge/bulb. 

ERROR: unauthorized user for group 1

[[{'error': {'type': 1,
    'address': '/groups',
    'description': 'unauthorized user'}}]]
