### ISSUE TITLE
run_scene error

### ISSUE THREAD

**Issue by Psychokiller1888** [studioimaginaire/phue#129]
Hello!
Thank you for your hardwork on this awesome package! I've run into an error:

> Traceback (most recent call last):
>   File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
>     msg = self.format(record)
>   File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
>     return fmt.format(record)
>   File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
>     record.message = record.getMessage()
>   File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
>     msg = msg % self.args
> TypeError: not enough arguments for format string
> Logged from file phue.py, line 1187

When using "run_scene". I call run_scene with both group_name and scene_name of course. This only happens when the scene requested doesn't exist in the given group.

**Could you also make "run_scene" return a boolean if it succeeded?**

**Comment by Psychokiller1888** [comment]
I don't get the logger problem. Well, there's a little issue, in the logger.warn, the tuple should be (scene_name, group_name) but still error thrown about not enough args
