### ISSUE TITLE
Instructions for installing and using for python newbie

### ISSUE THREAD

**Issue by pjsquared** [studioimaginaire/phue#2]
I am very new to python and have tried many ways to access the hues with no luck. i would very much like to use this but have no clue how to install and get going. could someone help please.

**Comment by Philipnah** [comment]
I'm getting this error can somebody help me with this?

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\phue.py", line 736, in connect
    with open(self.config_file_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Philip\\.python_hue'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "huebridge.py", line 3, in <module>
    b = Bridge("192.168.0.52")
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\phue.py", line 629, in __init__
    self.connect()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\phue.py", line 752, in connect
    self.register_app()
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\phue.py", line 706, in register_app
    response = self.request('POST', '/api', registration_request)
  File "C:\Program Files (x86)\Python37-32\lib\site-packages\phue.py", line 653, in request
    connection.request(mode, address, json.dumps(data))
  File "C:\Program Files (x86)\Python37-32\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files (x86)\Python37-32\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files (x86)\Python37-32\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files (x86)\Python37-32\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "C:\Program Files (x86)\Python37-32\lib\http\client.py", line 956, in send
    self.connect()
  File "C:\Program Files (x86)\Python37-32\lib\http\client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Program Files (x86)\Python37-32\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\Program Files (x86)\Python37-32\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [WinError 10013]

**Comment by Philipnah** [comment]
I'm sorry I don't know what you mean. I'm kind of a beginner. Could you be more specific? 
Thanks in advance.
