### ISSUE TITLE
does not deal well if lights don't start with #1

### ISSUE THREAD

**Issue by sawall** [studioimaginaire/phue#51]
It seems like, in some places, the library assumes that lights will be sequentially ordered starting with one. I have a bridge that a friend gave me and bought a new bulb which it's calling '4'. It's the bulb I've got in the following cases.

```
> lights = b.lights
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/python2.7/site-packages/phue.py", line 611, in lights
    return self.get_light_objects()
  File "/lib/python2.7/site-packages/phue.py", line 588, in get_light_objects
    return [self.lights_by_id[x] for x in range(1, len(self.lights_by_id) + 1)]
KeyError: 1
```

`lights = b.get_light_objects('id')` gets a correct list. If I do `l = lights[4]` I get the right light because it's the key. However, I still experience some weird behavior after this point. `l.saturation = 200` works fine, but this breaks, which looks like some kind of list/dictionary confusion that I don't quite grok:
```
> l.saturation = 189 + random.random() * 65
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/python2.7/site-packages/phue.py", line 207, in saturation
    self._set('sat', self._saturation)
  File "/lib/python2.7/site-packages/phue.py", line 106, in _set
    return self.bridge.set_light(self.light_id, *args, **kwargs)
  File "/lib/python2.7/site-packages/phue.py", line 685, in set_light
    if 'error' in list(result[-1][0].keys()):
IndexError: list index out of range
```

**Comment by carlosperate** [comment]
Just to clarify, does the bridge not have bulbs 1 to 3 configured? (even if they are not available or reachable, as you only have bulb 4)

**Comment by natcl** [comment]
Is this with phue 0.8 or the latest code from github ?
There was a fix recently dealing with this but perhaps we forgot some sections.

**Comment by sawall** [comment]
@carlosperate The bridge had bulbs 1-3 configured, but I didn't have the bulbs. I added a new bulb, which the bridge assigned id 4 to. Then I deleted bulbs 1-3 with the Philips Hue app.

@natcl It's with phue 0.8, which I grabbed from pip. I looked to see if there was a closed issue but I guess I missed it - I'll see if I've still got my issue with whatever's current here on github, thanks!

**Comment by sloria** [comment]
I've also run into this problem. I'll send a PR to fix this.

**Comment by sloria** [comment]
Ah actually, it looks like this has been resolved by this line: https://github.com/studioimaginaire/phue/blob/master/phue.py#L602 . I think this issue can be closed.

**Comment by craigcabrey** [comment]
Also ran into this issue. Would be fixed by releasing an update to the 0.8 series. But an easy work around for anyone reading is just calling `bridge.lights_by_id.values()`.

**Comment by WayneKeenan** [comment]
+1 on pushing an update and the version installed via pip has this issue.

**Comment by natcl** [comment]
Will push an update soon, just need to update the changlog and such first.
