### ISSUE TITLE
Problem with Living White Plug - has no colormode

### ISSUE THREAD

**Issue by jwildeboer** [studioimaginaire/phue#8]
I have several Living White plugs in my system. They have no colormode attached to it, making phue fail when you try to get lights:

Traceback (most recent call last):
  File "./dumpscene.py", line 34, in <module>
    dump_light(light)
  File "./dumpscene.py", line 16, in dump_light
    if light.colormode:
  File "/opt/hue/phue.py", line 138, in colormode
    self._colormode = self._get('colormode')
  File "/opt/hue/phue.py", line 75, in _get
    return self.bridge.get_light(self.light_id, _args, *_kwargs)
  File "/opt/hue/phue.py", line 534, in get_light
    return state['state'][parameter]
KeyError: 'colormode'

So self._get('colormode') should be able to return None, I guess?

Here the dump from a Living White plug straight from clip debugger on my bridge:

{
    "state": {
        "on": true,
        "bri": 254,
        "alert": "none",
        "effect": "none",
        "reachable": true
    },
    "type": "Dimmable plug-in unit",
    "name": "BedroomMusic",
    "modelid": "LWL001",
    "swversion": "1.0.1.4591",
    "pointsymbol": {
        "1": "none",
        "2": "none",
        "3": "none",
        "4": "none",
        "5": "none",
        "6": "none",
        "7": "none",
        "8": "none"
    }
}

As you can see, state has no color information at all. AFAICS without being a developer, this makes phues fail where it should fall back graciously somehow.

Maybe add a colormode "none" or "switch" or "dimmer"?

Jan

**Comment by jwildeboer** [comment]
I think it is safe to say this issue is not that popular ;-)
