### ISSUE TITLE
Can't connect to the bridge

### ISSUE THREAD

**Issue by DanielsCode** [studioimaginaire/phue#86]
I installed phue via pip on a raspberry pie model b and tried the following script:
```
#!/usr/bin/python
from phue import Bridge
b = Bridge('192.168.178.56')
# If the app is not registered and the button is not pressed, press the button and call connect() (this only needs to be run a single time)
b.connect()
b.get_api()
```

But I get always the following log message: 
`Traceback (most recent call last):
  File "test.py", line 5, in <module>
    b = Bridge('192.168.178.56')
  File "/usr/local/lib/python2.7/dist-packages/phue.py", line 629, in __init__
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/phue.py", line 753, in connect
    self.register_app()
  File "/usr/local/lib/python2.7/dist-packages/phue.py", line 707, in register_app
    response = self.request('POST', '/api', data)
  File "/usr/local/lib/python2.7/dist-packages/phue.py", line 653, in request
    connection.request(mode, address, data)
  File "/usr/lib/python2.7/httplib.py", line 1039, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1073, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1035, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 879, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 841, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 822, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
socket.error: [Errno 111] Connection refused`

Any ideas?

Thanks
Daniel

**Comment by caedn** [comment]
Are you sure that you have the right IP? Can you ping the IP from your Pi?

How about accessing http://192.168.178.56 from a browser on your Pi? 
Or check with something like nmap if port 80 is open?
